FROM node:14.17.3 as build-deps
ENV MAX_OLD_SPACE_SIZE=512
ENV CI=true
ARG DATABASE_URL
ARG HTTP_PROVIDER
ARG PRIVATE_KEY
ARG ADDRESS_FROM
ARG AWS_ACCESS_KEY_ID
ARG AWS_ACCESS_SECRET
ARG AWS_REGION
ARG AWS_BUCKET_NAME
ARG AWS_S3_STORAGE_CLASSES
ARG STRAPI_WORK_URL_FOR_QUERY_WEB3
ARG TOKEN_KEY
ARG TWITTER_CONSUMER_KEY
ARG TWITTER_CONSUMER_SECRET
ARG FRONTEND_URL
ARG TWITTER_AUTH_TOKEN
ARG DISCORD_CLIENT_ID
ARG DISCORD_CLIENT_SECRET
ARG DISCORD_REDIRECT_URL
ARG OPENAI_API_KEY
ARG SENDGRID_API_KEY

ENV DATABASE_URL $DATABASE_URL
ENV HTTP_PROVIDER $HTTP_PROVIDER
ENV PRIVATE_KEY $PRIVATE_KEY
ENV ADDRESS_FROM $ADDRESS_FROM
ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_SECRET $AWS_ACCESS_SECRET
ENV AWS_REGION $AWS_REGION
ENV AWS_BUCKET_NAME $AWS_BUCKET_NAME
ENV AWS_S3_STORAGE_CLASSES $AWS_S3_STORAGE_CLASSES
ENV STRAPI_WORK_URL_FOR_QUERY_WEB3 $STRAPI_WORK_URL_FOR_QUERY_WEB3
ENV TOKEN_KEY $TOKEN_KEY
ENV TWITTER_CONSUMER_KEY $TWITTER_CONSUMER_KEY
ENV TWITTER_CONSUMER_SECRET $TWITTER_CONSUMER_SECRET
ENV FRONTEND_URL $FRONTEND_URL
ENV TWITTER_AUTH_TOKEN $TWITTER_AUTH_TOKEN
ENV DISCORD_CLIENT_ID $DISCORD_CLIENT_ID
ENV DISCORD_CLIENT_SECRET $DISCORD_CLIENT_SECRET
ENV DISCORD_REDIRECT_URL $DISCORD_REDIRECT_URL
ENV OPENAI_API_KEY $OPENAI_API_KEY
ENV SENDGRID_API_KEY $SENDGRID_API_KEY

WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn
COPY . ./
COPY ./custom_modules ./node_modules
RUN yarn build clear

ENTRYPOINT ["/bin/sh", "-c" , "mkdir -p /usr/src/app/public/uploads && yarn start"]
